[build]
  functions = "functions"
  publish = "public"

  [functions]
node_bundler = "esbuild"
external_node_modules = ["express"]


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
